baseURL: 'https://inspired-beings.com/'
languageCode: 'en'
title: 'Inspired Beings'

# Images
# https://gohugo.io/content-management/image-processing/#imaging-configuration
imaging:
  hint: photo
  quality: 96
  resampleFilter: Lanczos

# Internationalization
# https://gohugo.io/content-management/multilingual/
# https://gohugo.io/content-management/page-resources/#multilingual
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: false

# Markup
# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
  goldmark:
    renderer:
      unsafe: true

# SEO
permalinks:
  page:
    /: /:slug/

# Taxonomies
disableKinds:
  - taxonomy
  - term
